### ISSUE TITLE
Uncertainty regarding caching for multiple different docker images in the same pipeline

### ISSUE THREAD

**Issue by LasseGravesen** [Drillster/drone-volume-cache#22]
Given the following pipeline, I am having trouble getting it to successfully cache the second publish step. If I use the cache_key option, I get the message 'No cache for /drone/docker' no matter how many times I run it. Am I missing something obvious? 

    pipeline:
      restore-cache-base:
        image: drillster/drone-volume-cache
        restore: true
        environment:
          STEP_TAG: 'BASE'
        cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH, STEP_TAG ]
        mount:
          - /drone/docker
        volumes:
          - /tmp/cache:/cache
      publish-base:
        image: plugins/docker
        registry: xxxx
        repo: yyyy
        dockerfile: Dockerfile.base
        tags:
          - latest
          - ${DRONE_COMMIT_BRANCH}
          - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
        secrets:
          - docker_username
          - docker_password
        storage_path: /drone/docker
        purge: false
      rebuild-cache-base:
        image: drillster/drone-volume-cache
        rebuild: true
        environment:
          STEP_TAG: 'BASE'
        cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH, STEP_TAG ]
        mount:
          - /drone/docker
        volumes:
          - /tmp/cache:/cache
          
      restore-cache-zerg:
        image: drillster/drone-volume-cache
        restore: true
        environment:
          STEP_TAG: 'ZERG'
        cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH, STEP_TAG ]
        mount:
          - /drone/docker
        volumes:
          - /tmp/cache:/cache
      publish-zerg:
        image: plugins/docker
        registry: xxxx
        repo: zzzz
        dockerfile: Dockerfile.zerg
        tags:
          - latest
          - ${DRONE_COMMIT_BRANCH}
          - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
        secrets:
          - docker_username
          - docker_password
        storage_path: /drone/docker
        purge: false
      rebuild-cache-zerg:
        image: drillster/drone-volume-cache
        rebuild: true
        environment:
          STEP_TAG: 'ZERG'
        cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH, STEP_TAG ]
        mount:
          - /drone/docker
        volumes:
          - /tmp/cache:/cache

**Comment by mjwwit** [comment]
It doesn't work if you merge the cache steps like so?

```yml
pipeline:
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH ]
    mount:
      - /drone/docker
    volumes:
      - /tmp/cache:/cache

  publish-base:
    image: plugins/docker
    registry: xxxx
    repo: yyyy
    dockerfile: Dockerfile.base
    tags:
      - latest
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    secrets:
      - docker_username
      - docker_password
    storage_path: /drone/docker
    purge: false

  publish-zerg:
    image: plugins/docker
    registry: xxxx
    repo: zzzz
    dockerfile: Dockerfile.zerg
    tags:
      - latest
      - ${DRONE_COMMIT_BRANCH}
      - ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    secrets:
      - docker_username
      - docker_password
    storage_path: /drone/docker
    purge: false

  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH ]
    mount:
      - /drone/docker
    volumes:
      - /tmp/cache:/cache
```
