### ISSUE TITLE
No cache for ./node_modules

### ISSUE THREAD

**Issue by imteekay** [Drillster/drone-volume-cache#29]
I'm running this plugin in our CI (drone v0.8) but it seems that it doesn't cache the node modules folder.

My pipeline looks like this:

```yaml
restore-cache:
  image: drillster/drone-volume-cache
  restore: true
  cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH]
  mount:
    - ./node_modules
  volumes:
    - /tmp/cache

install:
  image: node:14.15.4
  commands:
    - npm install

rebuild-cache:
  image: drillster/drone-volume-cache
  rebuild: true
  cache_key: [DRONE_REPO_OWNER, DRONE_REPO_NAME, DRONE_BRANCH]
  mount:
    - ./node_modules
  volumes:
    - /tmp/cache
```

In the first commit, I get this from the `rebuild-cache` step

```
Rebuilding cache for folder ./node_modules...
```

In the second commit, I get a `No cache for ./node_modules`.

Am I missing anything here in these steps?
