### ISSUE TITLE
Inconsistent failures

### ISSUE THREAD

**Issue by francisdb** [Drillster/drone-volume-cache#4]
This succeeds without errors

```
  volume-cache-rebuild:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - /drone/.coursier
      - /drone/.sbt
      - /drone/.ivy2
```

```
Rebuilding cache for /drone/.coursier...
rsync: change_dir "/drone/.coursier" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
Rebuilding cache for /drone/.sbt...
Rebuilding cache for /drone/.ivy2...

exit code 0
```

But if I put the non-existent folder as last mount entry the build step fails

```
...
Rebuilding cache for /drone/.coursier...
rsync: change_dir "/drone/.coursier" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]

exist code 23
```

I would expect this to consistently fail or ignore however I define the mounts
